### ISSUE TITLE
Historia de usuario #003 - Agregar mensaje para limitar la cantidad de átomos en pantalla

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#34]
Criterio de aceptación 2: Dado que el usuario selecciona Agregar átomo,se validará la cantidad máxima de elementos en espacio de trabajo. si hay 216 elementos y se quiere agregar uno nuevo, se muestra mensaje de información: ”Sin espacio para nuevo átomo”.

No se informa ningún mensaje indicando que se ha superado la cantidad máxima de átomos a mostrar en pantalla. (En el último release se probaron hasta 216 átomos máximos).

**Comment by mgallo2019** [comment]
Se verifica que si se spawnea desde la tabla periodica si esta controlado pero si se agrega solo ATOMO no muestra popup y aviso

**Comment by ldgobbi** [comment]
Esto no se va a hacer por lo mismo que los demás issues. El botón de agregar se deshabilita cuando se alcanza la cantidad máxima de elementos, no hace falta un pop-up.

**Comment by ldgobbi** [comment]
Cierro esto?
