### ISSUE TITLE
Historia de usuario #007 - Agregar mensaje limitador de máx cant de neutrones

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#35]
Criterio de aceptación 2: Dado un átomo seleccionado, cuando el alumno/profesor indica agregar neutrón, entonces se agrega 1 (uno) neutrón al átomo seleccionado. Si la cantidad ingresada llega a 176 un mensaje indicará en pantalla “Ha alcanzado la máxima cantidad válida de neutrones que puede tener un átomo”.

No muestra mensaje indicando que ya hay 176 neutrones en el átomo seleccionado.

**Comment by mgallo2019** [comment]
Agregaria lo de protones

**Comment by lucasmfrancini** [comment]
Sí. Y limitar que no se permitan más de 176.

**Comment by mgallo2019** [comment]
176 cual?

**Comment by mgallo2019** [comment]
protones es 118 y no esta en las historias de pruebas

**Comment by mgallo2019** [comment]
se soluciona con el PR #50

**Comment by ldgobbi** [comment]
Listo para probar en develop. Cierro.
