### ISSUE TITLE
Historia de usuario #008- Advertir cuando se quiere quitar neutrones y ya no hay

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#36]
Criterio de aceptación 2: Dado un átomo seleccionado, cuando el alumno/profesor selecciona el botón “-N”, y ya no hay más neutrones en pantalla, entonces se muestra un popup indicando: “El átomo seleccionado ya no tiene neutrones.”

No muestra mensaje indicando que no hay más neutrones a eliminar en el átomo seleccionado.

**Comment by mgallo2019** [comment]
Se podria tener la misma logica que en issue #010? por ej? sin popup

**Comment by ldgobbi** [comment]
Sí, no agrega mucho el pop-up

**Comment by lucasmfrancini** [comment]
Si, cierrenla por favor. Gracias.
