### ISSUE TITLE
Historia de usuario #009 - Agregar electrón según modelo de Linus Pauling

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#37]
Criterio de aceptación 1: Dado un átomo seleccionado en el modo “Normal”, cuando el alumno/profesor selecciona el botón “+E”, entonces se agrega un electrón a la órbita correspondiente según se determine de acuerdo modelo de diagonales de Linus Pauling, para determinar la órbita de asignación de los electrones.

El átomo no se incorpora en el orden que especifica el modelo de diagonales de Linus Pauling.

**Comment by ldgobbi** [comment]
Este problema debería estar resuelto cuando se mergee el PR #45

**Comment by ldgobbi** [comment]
PR #45 fue mergeado, ya pueden probar en develop. Si sigue el problema reabran el issue.
