### ISSUE TITLE
Historia de usuario #009 - Agregar electrón al átomo seleccionado.

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#38]
Criterio de aceptación 2: Dado un átomo seleccionado en el modo “normal”, cuando el alumno/profesor selecciona el botón “+E”, entonces se agrega un electrón a la órbita correspondiente según se determine de acuerdo modelo de diagonales de Linus Pauling, para determinar la órbita de asignación de los electrones y si el electrón debe ir a una órbita que no está en pantalla, la misma será creada.

El átomo no se incorpora en el orden que especifica el modelo de diagonales de Linus Pauling.

**Comment by ldgobbi** [comment]
Este issue ya fue reportado en https://github.com/AliMatias/SIAMM/issues/37.
Entiendo que este criterio de aceptación se diferencia al primero porque incluye la creación de una nueva órbita, lo cual no estaría fallando. 

Cierro el issue.
