### ISSUE TITLE
Historia de usuario #009 - Mostrar mensaje al agregar máximo de electrones

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#39]
Criterio de aceptación 3: Dado un átomo seleccionado en en el modo “normal”, cuando el alumno/profesor selecciona el botón “+E” y ya hay 280 electrones en el átomo seleccionado, entonces se muestra un popup para informar “El átomo seleccionado llegó a la cantidad máxima de electrones.”.

No se muestra el popup.

**Comment by mgallo2019** [comment]
El modelo de diagonales esta planificado en el sprint actual, que aun no se desarrollo

**Comment by ldgobbi** [comment]
Entiendo que este issue es sobre la falta del pop-up indicando que no se pueden ingresar mas electrones y no sobre la manera en que se incorporan. 

Lo digo por:
> El átomo no se incorpora en el orden que especifica el modelo de diagonales de Linus Pauling.

Esto ya esta reportado en https://github.com/AliMatias/SIAMM/issues/37

**Comment by lucasmfrancini** [comment]
~Lo cierro porque se maneja en otro issue.~

Edit by @ldgobbi: Se editó la descripción del issue

**Comment by ldgobbi** [comment]
Este problema debería estar resuelto cuando se mergee el PR #45

**Comment by ldgobbi** [comment]
PR #45 fue mergeado, ya pueden probar en develop. Si sigue el problema reabran el issue.
