### ISSUE TITLE
Historia de usuario #009 - Limitar la agregación de electrones

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#40]
Criterio de aceptación 4: Dado un átomo seleccionado en el modo “normal”, cuando el alumno/profesor selecciona el botón “+E” y ya hay 280 electrones en el átomo seleccionado, entonces se muestra un popup para informar “El átomo seleccionado llegó a la cantidad máxima de electrones.”, pero se permite seguir agregando electrones.

No se muestra mensaje indicando que se ha superado la cantidad de electrones en el átomo seleccionado.

**Comment by ldgobbi** [comment]
No estoy de acuerdo en que se puedan agregar más de 280 electrones.
Sugiero que aparezca un pop-up a los 118 electrones indicando que "Se alcanzó la cantidad máxima de electrones en elementos conocidos" o algo similar, y otro pop-up que informe a los 280 que "El átomo seleccionado llegó a la cantidad máxima de electrones.” y no se permitan seguir ingresando.

**Comment by ldgobbi** [comment]
Por otro lado, para tener una mejor organización y trazabilidad de los issues pido que los títulos no sean todos iguales por mas que pertenezcan a la misma historia.

Sugiero seguir la siguiente notación _"[HU-XXX: Nombre historia] - Descripcion breve del problema"_, por ejemplo: **"[HU-009: Agregar electrón] - Falta de alerta al alcanzar cantidad maxima de electrones"**

**Comment by lucasmfrancini** [comment]
> No estoy de acuerdo en que se puedan agregar más de 280 electrones.
> Sugiero que aparezca un pop-up a los 118 electrones indicando que "Se alcanzó la cantidad máxima de electrones en elementos conocidos" o algo similar, y otro pop-up que informe a los 280 que "El átomo seleccionado llegó a la cantidad máxima de electrones.” y no se permitan seguir ingresando.

De acuerdo con esto Gobb Master.

**Comment by ldgobbi** [comment]
Este problema debería estar resuelto cuando se mergee el PR #45

**Comment by mgallo2019** [comment]
Leo, lo dejo en el PR, pero para confirmar, el boton de + electrones sigue activo luego de alcanzar los 280, eso queda asi.. porque escuche el sabado que se iba a deshabilitar el boton +. (no me parece necesario.. igual), si se llega a 280 muestra 1ra vez el popup y luego si se quiere seguir agregando por mas que se aprieta el +, no agrega nada ni tampoco muestra de nuevo el popup.

**Comment by ldgobbi** [comment]
Sí, lo hice así

**Comment by ldgobbi** [comment]
PR #45 fue mergeado, ya pueden probar en develop. Si sigue el problema reabran el issue.
