### ISSUE TITLE
Historia de usuario #010 - Distribuir los electrones según modelo de Linus Pauling

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#41]
Criterio de aceptación 1: Dado un átomo seleccionado en el modo “normal”, cuando el alumno/profesor selecciona el botón “-E”, entonces se quita 1 (uno) electrón de la órbita correspondiente según modelo de diagonales de Linus Pauling, para determinar la órbita que perderá el electrón.

El electrón no se incorpora en el orden que especifica el modelo de diagonales de Linus Pauling.

**Comment by ldgobbi** [comment]
Este problema debería estar resuelto cuando se mergee el PR https://github.com/AliMatias/SIAMM/pull/45

**Comment by ldgobbi** [comment]
PR #45 fue mergeado, ya pueden probar en develop. Si sigue el problema reabran el issue.
