### ISSUE TITLE
Historia de usuario #010 - Quitar electrón al átomo seleccionado.

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#42]
Criterio de aceptación 2: Dado un átomo seleccionado en el modo “normal”, cuando el alumno/profesor selecciona el botón “-E”, entonces se quita 1 (uno) electrón de la órbita correspondiente según modelo de diagonales de Linus Pauling, para determinar la órbita que perderá el electrón y si dicha órbita hubiera quedado sin electrones desaparecerá.

El átomo no se incorpora en el orden que especifica el modelo de diagonales de Linus Pauling.

**Comment by ldgobbi** [comment]
Al igual que el issue https://github.com/AliMatias/SIAMM/issues/38, el problema de quitar el átomo según las diagonales ya fue reportado en https://github.com/AliMatias/SIAMM/issues/41.
Las órbitas se están eliminando una vez que se quedan sin electrones.
Cierro el issue.
