### ISSUE TITLE
Historia de usuario #010 - Avisar cuando no hay más electrones

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#43]
Criterio de aceptación 3: Dado un átomo seleccionado en el modo “normal”, cuando el alumno/profesor selecciona el botón “-E”, y ya no hay más electrones en pantalla, entonces se muestra un popup indicando: “El átomo seleccionado ya no tiene electrones.”

No se muestra mensaje indicando que no hay más electrones en el átomo seleccionado.

**Comment by ldgobbi** [comment]
No me parece necesario mostrar un mensaje para esto. Agregar pop-ups no siempre mejora la experiencia de usuario.
Me parece suficiente con que el contador de electrones muestre que está en 0 y al presionar no suceda nada.
Si estás de acuerdo cerra el issue.

**Comment by lucasmfrancini** [comment]
De acuerdo con esto gobb.

**Comment by ldgobbi** [comment]
Cierro el issue entonces
