### ISSUE TITLE
Distribución de electrones

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#44]
Verificar la distribución de los electrones al agregarse en las óribtas ya que no es simétrica, se incorporan en cualquier lugar y quedan electrones pegados. Ver si es posible de resolver esto cuando se aplique el modelo de la diagonal, sino descartar.

**Comment by ldgobbi** [comment]
Dejo abierto, pero no se va a trabajar en la solución en lo que queda del año

**Comment by lucasmfrancini** [comment]
Listo entonces cerrala
