### ISSUE TITLE
Historia de usuario #011 - Deshabilitar botones al abrir tabla periódica

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#47]
Se verifica que al abrir la tabla periódica los siguientes botones continúan habilitados dentro del 
panel desplegable de átomos

-AGREGAR
-ELIMINAR

Si la tabla periódica está activa, éstos botones deben permanecer grisados.

**Comment by mgallo2019** [comment]
Se soluciona en el branch RoyCastFix

**Comment by mgallo2019** [comment]
Se soluciona en #96
