### ISSUE TITLE
Superposición de elemtentos en pantalla

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#49]
Al interactuar con los diferentes botones en pantalla, si debajo del mismo justo se encuentra posicionado un átomo/molécula (dependiendo de la posición de la cámara), cuando se quiere interactuar con el botón se selecciona/deselecciona el elemento.

**Comment by mgallo2019** [comment]
Se soluciona en el branch RoyCastFix

**Comment by mgallo2019** [comment]
Se soluciona en #96
