### ISSUE TITLE
Btn Toggle  Combine, inicia Inactivo.

### ISSUE THREAD

**Issue by mgallo2019** [AliMatias/SIAMM#54]
El boton de cambios de modos aparece inactivo al momento de la carga final. 
Se tiene que presionar el boton INFO y recien ahi funciona.

**Comment by mgallo2019** [comment]
Se toma en la rama TperFixScale...

**Comment by mgallo2019** [comment]
Se va a implementar una mejora directamente en el Diseño del panel, aunque se haya solucionado.

**Comment by ldgobbi** [comment]
Se mergeo la solución temporal con el PR https://github.com/AliMatias/SIAMM/pull/55. Cierro el issue.
