### ISSUE TITLE
Excepcion Null Reference - Sugerencias

### ISSUE THREAD

**Issue by mgallo2019** [AliMatias/SIAMM#56]
Al momento de agregar otro elemento al canvas desde la tabla periodica, si ya se abrio previamente alguna vez el panel de Info adicional / sugerencias, arroja null reference en el metodo "updateelement"

**Comment by ldgobbi** [comment]
Revisándolo un poco mejor, veo que el error se da cuando el panel está inactivo, si mantengo el panel abierto no hay drama. La excepción aparece si ya se abrio previamente alguna vez el panel y agrego un elemento **al estar cerrado**.

Se pone inactivo cuando llama al metodo de FadeOut al cerrar el panel.

**Comment by ldgobbi** [comment]
Corregí el error moviendo el seteo de la info del panel al `AtomManager`. Para que encuentre la referencia del panel una vez apenas arranca la aplicación y use siempre la misma.

De todas formas ocurre otra excepción, que también está en la última versión de develop (solo que no la veiamos porque nunca llegaba):
```
Coroutine couldn't be started because the the game object 'InfoPanel' is inactive!
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
UIFader:FadeOut(CanvasGroup) (at Assets/Scripts/UI/UIFader.cs:35)
UIFader:FadeInAndOut(CanvasGroup) (at Assets/Scripts/UI/UIFader.cs:61)
InputManager:Spawn() (at Assets/Scripts/Managers/InputManager.cs:49)
UnityEngine.Events.UnityEvent:Invoke()
ButtonHandler:OnPointerClick(PointerEventData) (at Assets/Scripts/UI/ButtonHandler.cs:17)
UnityEngine.EventSystems.EventSystem:Update()
```
Esto pasa cuando selecciono un elemento de la tabla periódica y está cerrado el panel de información.
Hay algún bug con el UIFader. Ya había pasado algo así antes y lo solucioné agregando un override del método `FadeInAndOut`. Pero volvió en forma de InfoPanel

**Comment by ldgobbi** [comment]
@AliMatias podrás ayudarme a revisar esto del `UIFader`? En la rama `fix-null-reference-on-set-info-panel` subí los cambios que puse en el comentario anterior https://github.com/AliMatias/SIAMM/issues/56#issuecomment-526988852

**Comment by AliMatias** [comment]
Ok, hoy cuando llego a casa miro esto.

**Comment by AliMatias** [comment]
Se me ocurre otra manera de solucionarlo. Agregar un booleano a la clase del panel. Que tenga un getter y que los que van a llamar al panel al mètodo "setInfo" (que es donde explota). Primero chequee si esta activado. Asì nos evitamos modificar el UIFader que lo usan banda de clases.

EDIT: Estuve probando y no parece funcionar. Porque lo que queda nullReference es la variable que apunta al mainInfoPanel, y este esta desactivado. Voy a seguir mirando me parece un mejor approach este igual. Chequear antes de hacer la llamada

**Comment by ldgobbi** [comment]
Es que ese ya no es el problema, se soluciona con que lo maneje el AtomManager. Fijate que la excepcion esta pasa cuando hacés click en un boton de la tabla periódica y llama al UIFader para ocultar la tabla, no en el setInfo. 
Además me parece que lo debería setear igual el panel de info, aunque esté oculto/desactivado. Si no pasa que agrego un atomo con el panel cerrado, no se setea, abro el panel y esta vacio.

**Comment by AliMatias** [comment]
Ahhh entiendo entiendo.
Yo querìa desligarle responsabilidades al atommanager, pero bueno.
Me parece que se como solucionar eso (estaba probando esto x otro motivo).
![image](https://user-images.githubusercontent.com/22898752/64136200-79ab5100-cdc6-11e9-80c6-54aae508dcfb.png)
si te fijas en esa foto. El infoPanel es el que tiene los mètodos de setear. Y tambien tiene el UIFader asignado.
El "infoContainer", es el 'padre' de los items. Por lo tanto creo que sacando el UIFader de "infoPanel" y ponièndolo en "infoContainer", esto se solucionarìa. Es una teoria pero puede funcionar :P

**Comment by AliMatias** [comment]
Ahora estaba probando hacer eso y no pude, pero porque estaba sobre dev y no sobre tu rama. Ahora me tengo que ir a cocinar pero si podes intentar eso que dije genial, sino cuando tertmine de comer lo pruebo yo

**Comment by ldgobbi** [comment]
Nop. O no entendí o no funciona, probe pasando el script al container y poniendo como `uiElement` al container y al panel, si pongo al container se rompe lo de `setInfo` y la excepción salta aunque este abierto el panel, si pongo al panel se comporta igual que antes.
En ambos casos la excepción cambia a `Coroutine couldn't be started because the the game object 'InfoContainer' is inactive!`. Se ve que se queja del que tiene el script.

**Comment by AliMatias** [comment]
che sabes que me parece. 
![image](https://user-images.githubusercontent.com/22898752/64136664-a90f8d00-cdc9-11e9-98eb-2a55d020175a.png)
Ahi dice que info panel esta inactive. Pero si miras esa linea 49 en "inputManager" dice: 
UIFader.FadeInAndOut(tablaPeriodicaPanel);
Osea que esta intentando hacer fadeinandout de la tabla periodica. 
Pero debe estar agarrando otro "UIFader" de la escena porque no hay uno solo.
Lo agarra como "UIFader = FindObjectOfType<UIFader>();"
Por eos pienso que agarra otro que no es el que debe.

Intente asignarlo desde el editor pero el input manager esta adentro del prefab del boton de la tabla periodica y no se puede asignar un objeto de la escena al prefab.

Lo que se me ocurre que sea "FindObjectsOfType" que devuelve una lsita, y de alguna manera iterarlo y saber a quien pertenece el UIfader (Esto no se me ocurre como de una forma NO negrada)

**Comment by ldgobbi** [comment]
![imagen](https://user-images.githubusercontent.com/38298286/64136913-44edc880-cdcb-11e9-8cfe-5d46774f1ec3.png)

**Comment by AliMatias** [comment]
:/ lo que se me ocurre asi pensando rapido es hacer UIFader singleton, y que se usen siempre pasandole el canvasgroup por param.
Y cuando se necesita llamar desde un boton que el mismo panel o la clase monobehaviour pase x parametro (xq los botones no pueden mandar parametro)

**Comment by ldgobbi** [comment]
El prefab del `ElementBtn` que está dentro del InfoContainer es el mismo que el de los botones de la tabla periódica. Apenas arranca la aplicación el Awake del InputManager se instancia con el ElementBtn como parent. Cuando abris la tabla periodica se instancia para los botones de la tabla. No se si al ser todos el mismo prefab estará llamando a todas las instancias o como es la movida.

Edit: Na, creo que esto no tiene nada que ver

**Comment by ldgobbi** [comment]
Btw, no se que pasó ayer con github pero se rompieron algunos commits, la rama que habia hecho para corregir esto no deja compararla con develop ni hacer un PR. Asi que, para no tener problemas mas adelante, **la borro y creo una nueva** con los mismos cambios: https://github.com/AliMatias/SIAMM/tree/fix-null-on-set-info-panel-bis.

**Comment by mgallo2019** [comment]
Se soluciono con el PR #67
