### ISSUE TITLE
Electrones fuera de órbita

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#70]
Cuando se agregan rápidamente electrones los últimos se van escapando de la órbita.

[https://ibb.co/k4HFHgx](url)

**Comment by AliMatias** [comment]
Ese link que pusiste no funciona.
Sugerencia de solución: Deshabilitar la física en los electrones (pensé que esto ya era así).
Desventaja de esa solución: Si se agregan muchos, muy rápido, van a quedar superpuestos. Sigue siendo mejor antes que salgan volando.

**Comment by AliMatias** [comment]
Se resuelve en el siguiente PR.
https://github.com/AliMatias/SIAMM/pull/88
