### ISSUE TITLE
Superposición de funcionalidades al escribir nombres de moléculas

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#71]
Al escribir nombres de moléculas en el listado a filtrar se superponen las funcionalidades de teclado.
Por ejemplo: Si escribo AW mientras escribo se desplaza la vista en 1era persona por pantalla.. Si apreto la letra R, hace zoom al centro.

**Comment by mgallo2019** [comment]
Se soluciona en el Branch BlockingCamActions

**Comment by mgallo2019** [comment]
Solved #97
