### ISSUE TITLE
Historia de Usuario #015 - Botón de Tabla Periódica habilitado en modo Combinación

### ISSUE THREAD

**Issue by rodoalon** [AliMatias/SIAMM#73]
Al ingresar en el modo Combinar, queda habilitado el botón de Tabla periódica. Al seleccionar un elemento de la tabla periódica, se habilitan los botones de Agregar/Eliminar. Posible solución: Deshabilitar también el botón de tabla periódica impidiendo el ingreso de nuevos elementos. La creación de nuevos elementos se debe dar en el modo "Creación".

**Comment by ldgobbi** [comment]
Cambio el titulo al issue para que tenga la descripción del problema y no el nombre de la historia.

**Comment by ldgobbi** [comment]
Relacionado con #47

**Comment by mgallo2019** [comment]
Se soluciona en el branch RoyCastFix

**Comment by mgallo2019** [comment]
Se soluciona en #96
