### ISSUE TITLE
"Problema" con desplazamiento de los swipe button

### ISSUE THREAD

**Issue by lucasmfrancini** [AliMatias/SIAMM#89]
Si el Swipe button de los menú se abre con un click (sin deslizar), luego no responde a la acción si se lo quiere cerrar deslizándolo.
Si se abre deslizándolo y luego se hace click sobre el mismo, se bloquea también.
No se si es así la configuración del botón o no están funcionando correctamente (me inclino por la primera).
Sin embargo el usuario que lo use puede pensar que se le "trabó".

Lo dejo con prioridad baja.

**Comment by mgallo2019** [comment]
Si fue detectado por DESA y solucionado en la actual rama de "TIPSIAMM"

**Comment by mgallo2019** [comment]
Se resuelve en #92
